# Generated by Django 4.2.27 on 2026-01-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
